[package]
name = "excel-merger-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
build = "0.0.2"
calamine = "0.24.0"
rust_xlsxwriter = "0.64.2"
toml = "0.8.12"
